language: node_js

node_js:
    - '11.10.1'

os:
    - linux

cache: yarn

script:
    - yarn test
    - yarn build

deploy:
    - provider: npm
      email: $NPM_EMAIL
      api_token: $NPM_TOKEN
      on:
          branch: master
          tags: true
          repo: rmarganti/re-position

    - provider: pages
      token: $GH_TOKEN
      keep_history: true
      local_dir: .docz/dist
      on:
          branch: master
          tags: true
          repo: rmarganti/re-position
